{% set name = "nested-pandas" %}
{% set version = "0.6.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nested_pandas-{{ version }}.tar.gz
  sha256: 6d7621ab4ddb5d2d8b03981d261faeccb6ace365556b979e1f72b38c00325988

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=62
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=2
    - pandas >=2.2.3,<2.4
    - pyarrow >=16
    - Deprecated >=1.2.0
    - wrapt >=1.12.1
    - fsspec >=2025.7.0
    - universal_pathlib >=0.3.1

test:
  imports:
    - nested_pandas
  commands:
    - pip check
    - pytest tests/nested_pandas/series
    - pytest tests/nested_pandas/nestedframe/test_nestedframe.py
  requires:
    - pip
    - pytest
    - jinja2
    - python {{ python_min }}
  source_files:
    - tests

about:
  home: https://github.com/lincc-frameworks/nested-pandas
  summary: Efficient Pandas representation for nested associated datasets.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wilsonbb
    - smcguire-cmu
    - camposandro
    - OliviaLynn
    - delucchi-cmu
    - gitosaurus
    - dougbrn
    - hombit
