{% set name = "nested-pandas" %}
{% set version = "0.3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nested_pandas-{{ version }}.tar.gz
  sha256: a307a5e0a28d8ba37589856a6ecbeaa9b75f6dc91f36c545ba50047e669a2f3b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=62
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - pandas >=2.2,<2.3
    - pyarrow >=15

test:
  imports:
    - nested_pandas
  commands:
    - pip check
    - pytest tests/nested_pandas/series
    - pytest tests/nested_pandas/nestedframe/test_nestedframe.py
  requires:
    - pip
    - pytest
    - jinja2
    - python {{ python_min }}
  source_files:
    - tests

about:
  home: https://github.com/lincc-frameworks/nested-pandas
  summary: Efficient Pandas representation for nested associated datasets.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dougbrn
    - hombit
