{% set name = "nested-pandas" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nested_pandas-{{ version }}.tar.gz
  sha256: 829bb235a62c4b5ef38de0a04fef0e835b04671bf755c955e1a88dec32a00fef

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools >=62
    - setuptools-scm >=6.2
    - pip
  run:
    - python >=3.9
    - numpy
    - pandas >=2.2,<2.3
    - pyarrow >=15

test:
  imports:
    - nested_pandas
  commands:
    - pip check
    - pytest tests/nested_pandas/series
    - pytest tests/nested_pandas/nestedframe/test_nestedframe.py
  requires:
    - pip
    - pytest
  source_files:
    - tests

about:
  home: https://github.com/lincc-frameworks/nested-pandas
  summary: Efficient Pandas representation for nested associated datasets.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - dougbrn
    - hombit
